//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_NguyenThiThuHuong.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DATN_NguyenThiThuHuong.Common.Resources.ResourceVI", typeof(ResourceVI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không hợp lệ..
        /// </summary>
        public static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng thử lại..
        /// </summary>
        public static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ..
        /// </summary>
        public static string ErrorValidate {
            get {
                return ResourceManager.GetString("ErrorValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng file tải lên vượt quá {0}..
        /// </summary>
        public static string FileCapacityExceeded {
            get {
                return ResourceManager.GetString("FileCapacityExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hợp lệ..
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được vượt quá {0} ký tự..
        /// </summary>
        public static string InValidMaxLength {
            get {
                return ResourceManager.GetString("InValidMaxLength", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to không đúng định dạng..
        /// </summary>
        public static string NcorrectFormat {
            get {
                return ResourceManager.GetString("NcorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sự thay đổi..
        /// </summary>
        public static string NotContent {
            get {
                return ResourceManager.GetString("NotContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được để trống..
        /// </summary>
        public static string NotEmtity {
            get {
                return ResourceManager.GetString("NotEmtity", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ..
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
    }
}
